/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
//package javaapplication1;

/**
 *
 * @author Omotola
 */
 import javax.swing.*;
public class PuzzleApp extends javax.swing.JFrame {

    /**
     * Creates new form PuzzleApp
     */
    
    public PuzzleApp() {
        initComponents();
    }
    int count = 0;
    Puzzle jigsaw = new Puzzle();
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
		//private JPanel
        jPanel1 = new javax.swing.JPanel();
        Button_two = new javax.swing.JLabel();
        Button_one = new javax.swing.JLabel();
        Button_four = new javax.swing.JLabel();
        Button_three = new javax.swing.JLabel();
        Button_five = new javax.swing.JLabel();
        Button_six = new javax.swing.JLabel();
        Button_eight = new javax.swing.JLabel();
        Button_seven = new javax.swing.JLabel();
        Button_nine = new javax.swing.JLabel();
        jigsaw.array();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Button_two.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        //Button_two.setText("jsdkksldd");
        Button_two.setText(jigsaw.arr[1]);
        Button_two.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_twoMouseClicked(evt);
            }
        });

        Button_one.setBackground(new java.awt.Color(204, 204, 204));
        Button_one.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_one.setText(jigsaw.arr[0]);
        Button_one.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_oneMouseClicked(evt);
            }
        });

        Button_four.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_four.setText(jigsaw.arr[3]);
        Button_four.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_fourMouseClicked(evt);
            }
        });

        Button_three.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_three.setText(jigsaw.arr[2]);
        Button_three.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_threeMouseClicked(evt);
            }
        });

        Button_five.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_five.setText(jigsaw.arr[4]);
        Button_five.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_fiveMouseClicked(evt);
            }
        });

        Button_six.setBackground(new java.awt.Color(204, 204, 204));
        Button_six.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_six.setText(jigsaw.arr[5]);
        Button_six.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_sixMouseClicked(evt);
            }
        });

        Button_eight.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_eight.setText(jigsaw.arr[7]);
        Button_eight.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_eightMouseClicked(evt);
            }
        });

        Button_seven.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_seven.setText(jigsaw.arr[6]);
        Button_seven.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_sevenMouseClicked(evt);
            }
        });

        Button_nine.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        Button_nine.setText(jigsaw.arr[8]);
        Button_nine.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Button_nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Button_nineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Button_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_one, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_two, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Button_four, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Button_five, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Button_six, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_three, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_two, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_one, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_three, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Button_four, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_five, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_six, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_seven, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Button_eight, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Button_nine, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_oneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_oneMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 1");
        String [] adj ={"1","3"};
          //Button_one.setText(" ");
        for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])])== " "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[0]);////////
                Button_one.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[0];
                
                jigsaw.arr[0] = " ";
                
                //Button_one.setText(jigsaw.arr[Integer.valueOf(adj[i])]);
                break;
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
    }//GEN-LAST:event_Button_oneMouseClicked

    private void Button_twoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_twoMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 2");
        String [] adj ={"0","2","4"};
        for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])])==" "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[1]);
                Button_two.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[1];
                
                jigsaw.arr[1] = " ";
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
        count = 0;

    }//GEN-LAST:event_Button_twoMouseClicked

    private void Button_threeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_threeMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 3");
        String [] adj ={"1","5"};
        for(int i = 0; i < adj.length;i++){
            if (jigsaw.arr[Integer.valueOf(adj[i])]==" "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[2]);
                Button_three.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[2];
                
                jigsaw.arr[2] = " ";
                
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        	System.exit(0);
        }
		count = 0;
    }//GEN-LAST:event_Button_threeMouseClicked

    private void Button_fourMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_fourMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 4");
        String [] adj ={"0","4","6"};
        for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])])== " "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[3]);
                Button_four.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[3];
                
                jigsaw.arr[3] = " ";
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
		count = 0;
    }//GEN-LAST:event_Button_fourMouseClicked

    private void Button_fiveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_fiveMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 5");
        String [] adj ={"1","3","5","7"};
            for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])])== " "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[4]);
                Button_five.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[4];
                
                jigsaw.arr[4] = " ";
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
		count = 0;
    }//GEN-LAST:event_Button_fiveMouseClicked

    private void Button_sixMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_sixMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 6");
        String [] adj ={"2","4","8"};
            for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])])== " "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[5]);
                Button_six.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[5];
                
                jigsaw.arr[5] = " ";
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
		count = 0;
    }//GEN-LAST:event_Button_sixMouseClicked

    private void Button_sevenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_sevenMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 7");
        String [] adj ={"3","7"};
            for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])])== " "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[6]);
                Button_seven.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[6];
                
                jigsaw.arr[6] = " ";
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
		count = 0;
    }//GEN-LAST:event_Button_sevenMouseClicked

    private void Button_eightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_eightMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 8");
        String [] adj ={"4","6","8"};
        for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])]) == " "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[7]);
                Button_eight.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[7];
                
                jigsaw.arr[7] = " ";
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
		count = 0;
    }//GEN-LAST:event_Button_eightMouseClicked

    private void Button_nineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Button_nineMouseClicked
        // TODO add your handling code here:
        System.out.println("This is button 9");
        String [] adj ={"5","7"};
            for(int i = 0; i < adj.length;i++){
            if ((jigsaw.arr[Integer.valueOf(adj[i])])== " "){
                //swap method;
                returningButton((Integer.valueOf(adj[i])),jigsaw.arr[8]);
                Button_nine.setText(" ");
                jigsaw.arr[Integer.valueOf(adj[i])] = jigsaw.arr[8];
                
                jigsaw.arr[8] = " ";
                
            }
        }
        for (int i=1;i<=8;i++){
        	if(jigsaw.arr[i]==String.valueOf(i)){
        		count++;
        	}
        }
        if (count == 8){
        	JOptionPane.showMessageDialog(null,"BOOM\nYou Got It!!!");
        }
		count = 0;
    }//GEN-LAST:event_Button_nineMouseClicked
    private void returningButton(int i,String m){
    	switch(i){
    		case 0: Button_one.setText(m);
    		break;
    		case 1: Button_two.setText(m);
    		break;
    		case 2: Button_three.setText(m);
    		break;
    		case 3: Button_four.setText(m);
    		break;
    		case 4: Button_five.setText(m);
    		break;
    		case 5: Button_six.setText(m);
    		break;
    		case 6: Button_seven.setText(m);
    		break;
    		case 7: Button_eight.setText(m);
    		break;
    		case 8: Button_nine.setText(m);
        	}
    }/////////////////////
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuzzleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuzzleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuzzleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuzzleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PuzzleApp().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Button_eight;
    private javax.swing.JLabel Button_five;
    private javax.swing.JLabel Button_four;
    private javax.swing.JLabel Button_nine;
    private javax.swing.JLabel Button_one;
    private javax.swing.JLabel Button_seven;
    private javax.swing.JLabel Button_six;
    private javax.swing.JLabel Button_three;
    private javax.swing.JLabel Button_two;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
